// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ploch.EditorConfigTools.DataAccess;

#nullable disable

namespace Ploch.EditorConfigTools.Data.SqLite.Migrations
{
    [DbContext(typeof(EditorConfigDbContext))]
    partial class EditorConfigDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("ConfigSectionFileExtension", b =>
                {
                    b.Property<int>("ConfigSectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtensionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigSectionsId", "FileExtensionsId");

                    b.HasIndex("FileExtensionsId");

                    b.ToTable("ConfigSectionFileExtension");
                });

            modelBuilder.Entity("ConfigSectionTypeFileExtension", b =>
                {
                    b.Property<int>("ConfigSectionTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileExtensionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("ConfigSectionTypesId", "FileExtensionsId");

                    b.HasIndex("FileExtensionsId");

                    b.ToTable("ConfigSectionTypeFileExtension");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigEntryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigEntryId");

                    b.HasIndex("ConfigSectionId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigSectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SettingDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigSectionId");

                    b.HasIndex("SettingDefinitionId");

                    b.ToTable("ConfigEntries");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigSectionTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EditorConfigFileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePattern")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigSectionTypeId");

                    b.HasIndex("EditorConfigFileId");

                    b.ToTable("ConfigSections");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigSectionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedExtensions")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedExtensions");

                    b.ToTable("ConfigSectionTypes");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.EditorConfigFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRoot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("EditorConfigFiles");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.FileType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FilePattern");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.SettingCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("SettingCategories");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.SettingDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingNameRegex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SettingDefinitions");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ValueDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ValueTypeId");

                    b.ToTable("ValueDefinitions");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ValueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandlerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ValueTypes");
                });

            modelBuilder.Entity("SettingCategorySettingDefinition", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SettingDefinitionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoriesId", "SettingDefinitionsId");

                    b.HasIndex("SettingDefinitionsId");

                    b.ToTable("SettingCategorySettingDefinition");
                });

            modelBuilder.Entity("SettingDefinitionValueDefinition", b =>
                {
                    b.Property<int>("AllowedValuesId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ValueSettingDefinitionsId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedValuesId", "ValueSettingDefinitionsId");

                    b.HasIndex("ValueSettingDefinitionsId");

                    b.ToTable("SettingDefinitionValueDefinition");
                });

            modelBuilder.Entity("ConfigSectionFileExtension", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigSection", null)
                        .WithMany()
                        .HasForeignKey("ConfigSectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ploch.EditorConfigTools.Models.FileType", null)
                        .WithMany()
                        .HasForeignKey("FileExtensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConfigSectionTypeFileExtension", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigSectionType", null)
                        .WithMany()
                        .HasForeignKey("ConfigSectionTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ploch.EditorConfigTools.Models.FileType", null)
                        .WithMany()
                        .HasForeignKey("FileExtensionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ploch.EditorConfigTools.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.Comment", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigEntry", "ConfigEntry")
                        .WithMany("Comments")
                        .HasForeignKey("ConfigEntryId");

                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigSection", "ConfigSection")
                        .WithMany("Comments")
                        .HasForeignKey("ConfigSectionId");

                    b.Navigation("ConfigEntry");

                    b.Navigation("ConfigSection");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigEntry", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigSection", "ConfigSection")
                        .WithMany("ConfigEntries")
                        .HasForeignKey("ConfigSectionId");

                    b.HasOne("Ploch.EditorConfigTools.Models.SettingDefinition", "SettingDefinition")
                        .WithMany("ConfigEntries")
                        .HasForeignKey("SettingDefinitionId");

                    b.Navigation("ConfigSection");

                    b.Navigation("SettingDefinition");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigSection", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ConfigSectionType", "ConfigSectionType")
                        .WithMany("ConfigSections")
                        .HasForeignKey("ConfigSectionTypeId");

                    b.HasOne("Ploch.EditorConfigTools.Models.EditorConfigFile", "EditorConfigFile")
                        .WithMany("ConfigSections")
                        .HasForeignKey("EditorConfigFileId");

                    b.Navigation("ConfigSectionType");

                    b.Navigation("EditorConfigFile");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.EditorConfigFile", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.Project", "Project")
                        .WithMany("EditorConfigFiles")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.Project", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ApplicationUser", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.SettingCategory", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.SettingCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ValueDefinition", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ValueType", "ValueType")
                        .WithMany("ValueDefinitions")
                        .HasForeignKey("ValueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ValueType");
                });

            modelBuilder.Entity("SettingCategorySettingDefinition", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.SettingCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ploch.EditorConfigTools.Models.SettingDefinition", null)
                        .WithMany()
                        .HasForeignKey("SettingDefinitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SettingDefinitionValueDefinition", b =>
                {
                    b.HasOne("Ploch.EditorConfigTools.Models.ValueDefinition", null)
                        .WithMany()
                        .HasForeignKey("AllowedValuesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ploch.EditorConfigTools.Models.SettingDefinition", null)
                        .WithMany()
                        .HasForeignKey("ValueSettingDefinitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ApplicationUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigEntry", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigSection", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ConfigEntries");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ConfigSectionType", b =>
                {
                    b.Navigation("ConfigSections");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.EditorConfigFile", b =>
                {
                    b.Navigation("ConfigSections");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.Project", b =>
                {
                    b.Navigation("EditorConfigFiles");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.SettingCategory", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.SettingDefinition", b =>
                {
                    b.Navigation("ConfigEntries");
                });

            modelBuilder.Entity("Ploch.EditorConfigTools.Models.ValueType", b =>
                {
                    b.Navigation("ValueDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
