name: 'Test Report'
on:
  workflow_run:
    workflows: [ 'Build' ]                     # runs after CI workflow
    branches: '**'
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Test Report
        uses: phoenix-actions/test-reporting@v12
        id: test-report
        with:
          artifact: test-results
          name: 'Test Results'
          path: '**/TestResults/TestOutputResults.xml'
          reporter: dotnet-trx
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Read output variables
        run: |
          echo "url is ${{ steps.test-report.outputs.runHtmlUrl }}"
